---
title: "Pumpkin Bars"
format: html
---


## Ingredients

| Dry ingredient | Amount |
|---|---|
| Flour | 240 grams |
| Baking soda | 1 teaspoon |
| Baking powder | 1 teaspoon |
| Salt | ¾ teaspoon |
| Cinnamon | 1 ½ teaspoon |
| Allspice | ¼ teaspoon |
| Ground ginger | ¼ teaspoon |
| Nutmeg | ¼ teaspoon |

| Wet ingredient | Amount |
|---|---|
| Brown sugar | 200 grams | 
| White sugar | 50 grams |
| Eggs | 3 |
| Milk | ¼ cup |
| Pumpkin puree | 425 grams |
| Vegetable oil | ⅔ cup |
| Vanilla extract | 2 teaspoons |
| Salt | ½ teaspoon |
| Baking powder | ½ teaspoon |

## Cream Cheese Frosting

| Ingredient | Amount |
|---|---|
| Butter | 114 grams |
| Cream cheese | 226 grams |
| Powdered sugar | 340 grams 
| Vanilla extract | 1 teaspoon |


## Directions

1. In a bowl, start by sifting and combining all of the dry ingredients. Mix them well.

2. In a separate bowl, for the wet ingredients, whisk the eggs, white sugar, and the brown sugar. Whisk well.

3. Add the milk,  pumpkin, vegetable oil, and the vanilla to the wet mixture. Whisk well.

4. Pour the dry into the wet and fold the batter. Don’t over mix the batter.

5. Line a 10 x 15 baking sheet with parchment paper and pour the batter into the sheet.

6. Bake for about 25 minutes at 350℉. The internal temperature of should be 195-200℉.

7. Let the cake cool for about 10-15 minutes before transferring to a cooling rack.
